export enum UserError {
    DUPLICATED_EMAIL = 'DUPLICATED_EMAIL',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_CANNOT_BE_FOUND = 'USER_CANNOT_BE_FOUND',
    USER_CANNOT_BE_DELETED = 'USER_CANNOT_BE_DELETED',
    USER_CANNOT_BE_UPDATED = 'USER_CANNOT_BE_UPDATED',
    USER_CANNOT_BE_CREATED = 'USER_CANNOT_BE_CREATED',
}
