
export enum AuthError {
    DUPLICATED_EMAIL = 'DUPLICATED_EMAIL',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    CANNOT_AUTHENTICATE_USER = 'CANNOT_AUTHENTICATE_USER',
    INVALID_SESSION = 'INVALID_SESSION',
    NO_TOKEN_IN_HEADERS = 'NO_TOKEN_IN_HEADERS',
}
