
export enum AuthErrors {
    NOT_AUTHENTICATED = 'NOT_AUTHENTICATED',
    DUPLICATED_EMAIL = 'DUPLICATED_EMAIL',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    CANNOT_AUTHENTICATE_USER = 'CANNOT_AUTHENTICATE_USER',
}
