export enum QrCodeError {
    QR_CODE_NOT_FOUND = 'QR_CODE_NOT_FOUND',
    QR_CODE_CANNOT_BE_FOUND = 'QR_CODE_CANNOT_BE_FOUND',
    QR_CODE_CANNOT_BE_CREATED = 'QR_CODE_CANNOT_BE_CREATED',
    QR_CODE_CANNOT_BE_DELETED = 'QR_CODE_CANNOT_BE_DELETED',
    QR_CODE_CANNOT_BE_UPDATED = 'QR_CODE_CANNOT_BE_UPDATED',
    FORM_DESATIVATED_BY_THE_TEACHER = 'FORM_DESATIVATED_BY_THE_TEACHER',
}