
export enum GroupError {
    GROUP_NOT_FOUND = 'GROUP_NOT_FOUND',
    GROUP_GET_FAILED = 'GROUP_GET_FAILED',
    GROUP_DELETE_FAILED = 'GROUP_DELETE_FAILED',
    GROUP_CREATE_FAILED = 'GROUP_CREATE_FAILED',
    GROUP_UPDATE_FAILED = 'GROUP_UPDATE_FAILED',
}
