
export enum GroupError {
    GROUP_NOT_FOUND = 'GROUP_NOT_FOUND',
    GROUP_CANNOT_BE_FOUND = 'GROUP_CANNOT_BE_FOUND',
    GROUP_CANNOT_BE_CREATED = 'GROUP_CANNOT_BE_CREATED',
    GROUP_CANNOT_BE_DELETED = 'GROUP_CANNOT_BE_DELETED',
    GROUP_CANNOT_BE_UPDATED = 'GROUP_CANNOT_BE_UPDATED',
    GROUPS_CANNOT_BE_FOUND = 'GROUPS_CANNOT_BE_FOUND',
}
