
export enum RegistryError {
    REGISTRY_NOT_FOUND = 'REGISTRY_NOT_FOUND',
    REGISTRY_CANNOT_BE_FOUND = 'REGISTRY_CANNOT_BE_FOUND',
    REGISTRY_CANNOT_BE_DELETED = 'REGISTRY_CANNOT_BE_DELETED',
    REGISTRY_CANNOT_BE_UPDATED = 'REGISTRY_CANNOT_BE_UPDATED',
    REGISTRY_CANNOT_BE_CREATED = 'REGISTRY_CANNOT_BE_CREATED',
}